language: java
mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
mvn test -B

jdk:
  - openjdk8
  
  script:
  - jdk_switcher use oraclejdk8
  - # do stuff with Java 8
  - jdk_switcher use openjdk8
  - # do stuff with open Java 8
